#!/bin/sh

. "$H"/utils/utils

set -e

mkdir -p $C $S $BS

. $H/bootstrap/musl
. $H/bootstrap/binutils
. $H/bootstrap/gcc
. $H/bootstrap/busybox
. $H/bootstrap/m4
. $H/bootstrap/make
. $H/bootstrap/patch
. $H/bootstrap/mk
