#!/bin/sh

set -e

for f in core/*; do
	. $f/pkg-info
	DIR=${f%%/*}
	PKG=${f##*/}
	FULLNAME=$pkgname-$pkgver-$A-$pkgrev

	echo "#### $PKG"
	echo $DIR:V: $PKG
	echo $PKG:V: $P/$FULLNAME.tbz
	for d in $pkgbdeps; do
		echo rebuild-$PKG:V: install-$d
		echo $P/$FULLNAME.tbz: install-$d
	done
	for d in $pkgdeps; do
		echo install-$PKG:V: install-$d
	done
	echo $R/var/log/packages/$FULLNAME: install-$PKG
	echo install-$PKG:V: $P/$FULLNAME.tbz
	echo "  installpkg -r $R $P/$FULLNAME.tbz"
	echo $P/$FULLNAME.tbz:
	echo "  buildpkg $f"
	echo rebuild-$PKG:V:
	echo "  buildpkg $f"
done
