#!/bin/sh

set -e

for f in core/* devel/*; do
	. $f/pkg-info
	DIR=${f%%/*}
	PKG=${f##*/}
	FULLNAME=$pkgname-$pkgver-$A-$pkgrev

	echo "#### $PKG"
	echo $DIR:V: $PKG
	echo rebuild-$DIR:V: rebuild-$PKG
	echo install-$DIR:V: install-$PKG
	echo $PKG:V: $P/$FULLNAME.tbz
	for d in $pkgbdeps; do
		echo $P/$FULLNAME.tbz:V: install-$d
	done
	for d in $pkgdeps; do
		echo install-$PKG:V: install-$d
	done
	echo $R/var/log/packages/$FULLNAME: $P/$FULLNAME.tbz
	echo "  installpkg -r $R $P/$FULLNAME.tbz"
	echo install-$PKG:V: $R/var/log/packages/$FULLNAME
	echo $P/$FULLNAME.tbz: $f/pkg-*
	echo "  . utils/utils"
	echo "  buildpkg $f"
	echo "rebuild-$PKG:V:"
	echo "  . utils/utils"
	echo "  rebuildpkg $f"
done
