#!/bin/sh
# recipes - generate mkfile from package recipes

for f in stage0/*; do
  DIR=${f%%/*}
  PKG=$f
  echo $DIR:V: $PKG
  echo $PKG:V: "$R/var/logs/packages/$PKG"
  echo rebuild-$PKG:V:
  echo "  ##### $f"
  if [ -z "$N" ]; then
    echo "  . config"
    [ -n "$V" ] && echo "  set -x"
    echo "  makepkg -C $f -c \$D/makepkg.stage0.config"
    echo
  fi
done
