#!/bin/sh

uid="$(id -u)"
if [ "$uid" != "0" ]; then
    printf -- "need to be root. please enter password.\n"
    su -c "$0 $1"
    exit $?
fi

. "$H"/config

umount "$R/dev/pts"
umount "$R/dev/shm"
umount "$R/dev"
umount "$R/proc"
umount "$R/$BS"

