#!/bin/sh

download() {
    local try=0
    local limit=60
    local timeout=30
    local outfile="$C/${2:-`basename "$1"`}"

    if [ -e "$outfile" ]; then
	echo "found $outfile"
	return
    fi

    while [ $try -ne $limit ]; do
        try=$((try+1))
		if ! wget --no-check-certificate -O "$outfile" "$1" ; then
            printf -- "trouble downloading %s. fix your connection.\n" "$1"
            printf -- "%d tries remaining. waiting %d seconds\n" "$((limit-try))" "$timeout"
			sleep "$timeout"
		else
			# check if archive was completety downloaded
			# busybox' wget seem to be rather buggy
			if ! tar tf "$outfile" >/dev/null ; then
				echo "partial download detected, retrying..."
			else
				break
			fi
		fi
	done
}

extract() {
     cd "$S"
     tar xf "$C/$1"
}

rebuildpkg() {
	pkgname=
	pkgver= 
	pkgrev=  
	pkgdeps= 
	pkgbdeps=    
	set -e -x
	origin=`pwd`/"$1"
	. "$H"/config     
	. "$1"/pkg-info 
	echo "building $pkgname-$pkgver-$A-$pkgrev.tbz"
	. "$1"/pkg-build
}

buildpkg() {
	. "$1"/pkg-info
	pkgfile="$pkgname-$pkgver-$A-$pkgrev.tbz"
	if [ ! -e "$P/$pkgfile" ]; then
		rebuildpkg $1
	else
		echo "$pkgname: found $P/$pkgfile"
	fi
}
